#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoderr,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderl,       sensorQuadEncoder)
#pragma config(Motor,  port2,           frontr,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backr,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontl,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backl,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           flyr,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           flyl,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armt,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armb,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "functions.c"



task main(){
			//auto_spin_flywheel(118,8,true);
			motor[flyl] = -118;
			motor[flyr] = 118;
			wait1Msec(20000);
}
