#pragma config(Sensor, port1,  gyro,           sensorGyro)
#pragma config(Sensor, port11, encoderl,       sensorQuadEncoder)
#pragma config(Motor,  motor2,          frontr,        tmotorVexIQ, openLoop)
#pragma config(Motor,  motor3,          backr,         tmotorVexIQ, openLoop)
#pragma config(Motor,  motor4,          frontl,        tmotorVexIQ, openLoop)
#pragma config(Motor,  motor5,          backl,         tmotorVexIQ, openLoop)
#pragma config(Motor,  motor6,          flyr,          tmotorVexIQ, openLoop)
#pragma config(Motor,  motor7,          flyl,          tmotorVexIQ, openLoop)
#pragma config(Motor,  motor8,          armt,          tmotorVexIQ, openLoop)
#pragma config(Motor,  motor9,          armb,          tmotorVexIQ, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "functions.c"



task main(){
			motor[backl] = 118;
			wait1Msec(20000);
}
