#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "benFunctions.c"
//*!!It finally worked
//*!! ehh
//*!!
task main()
{
	while (true)
	{
		if (vexRT [Btn8D]==1)
		{
			clawOpen();
		}
		if (vexRT [Btn8R]==1)
		{
			clawClose();
		}
		if (vexRT [Btn8U]==1)
		{
			armUp();
		}
		if (vexRT [Btn8L]==1)
		{
			armDown();
		}
		{
		motor[port2] = vexRT[Ch2]/2;
		motor[port3] = vexRT[Ch3]/2;
		}
	}



}
