#pragma config(Motor,  port2,           tractor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightTopFly,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightLowFly,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftLowFly,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftTopFly,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
	motor[leftFront] = vexRT[Ch2];
	motor[leftBack] = vexRT[Ch2];
	motor[rightFront] = vexRT[Ch3];
	motor[rightBack] = vexRT[Ch3];
		if (vexRT [Btn6U]==1)
		{
		motor [leftTopFly]=120;
		motor [leftLowFly]=120;
		motor [rightTopFly]=-120;
		motor [rightLowFly]=-120;
		wait10Msec (0001);
		motor [leftTopFly]=0;
		}
		if (vexRT [Btn6D]==1)
		{
		motor [leftTopFly]=0;
		motor [leftLowFly]=0;
		motor [rightTopFly]=-0;
		motor [rightLowFly]=-0;
		wait10Msec (0001);
		motor [leftTopFly]=0;
		}
		if (vexRT [Btn5U]==1)
		{
		motor [tractor]=100;
		wait10Msec (300);
		motor [tractor]=0;
		}
		if (VexRT [Btn5D]==1)
		{
		motor [tractor]=-100;
		wait10Msec (300);
		motor [tractor]=0;
		}




	}
}
