#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoderr,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderl,       sensorQuadEncoder)
#pragma config(Motor,  port1,           exr,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,           frontr,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backr,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontl,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backl,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           flyr,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           flyl,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armt,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armb,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           exl,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * @file functions.c
 * @brief This file contains all functions to be used by
 * the competition code.
 *
 * @warning DO NOT compile this file
 * by itself, it will not work. Instead, save it
 * and compile main.c
 *
 * Also, you must include your motor and sensor setup somewhere in this file.
 *
 *
 */

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 CONSTANTS
//
/////////////////////////////////////////////////////////////////////////////////////////

#define TIMEOUT_CNT_PER_SEC    10   /*!< amount of timeout counts per second */
#define MOTOR_SPEED        		 118  /*!< default motor speed */

int frontLeftVal  = 0; /*!< value of the front left  motor */
int backLeftVal   = 0; /*!< value of the back  left  motor */
int frontRightVal = 0; /*!< value of the front right motor */
int backRightVal  = 0; /*!< value of the back  right motor */


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 DRIVETRAIN
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
* Clears all the motors
*
*/
void clearMotors(){
	//Set all motor values to 0
	frontLeftVal  = 0;
	backLeftVal   = 0;
	frontRightVal = 0;
	backRightVal  = 0;
}

/**
* Sets all motors to a certain value
*
*
* @param  speed   the speed of the motors
*/
void setMotors(int speed){
	//Set all motor values to power value
	frontLeftVal  = speed;
	backLeftVal   = speed;
	frontRightVal = speed;
	backRightVal  = speed;
}

/**
* Sets the left motors to a given speed
*
*
* @param  speed   the speed that the left motors will be set to
*
*/
void setMotorsLeft(int speed){
	frontLeftVal = speed;
	backLeftVal  = speed;
}

/**
* Sets the right motors to a given speed
*
*
* @param  speed   the speed that the right motors will be set to
*
*/
void setMotorsRight(int speed){
	frontRightVal = speed;
	backRightVal  = speed;
}

/**
* Runs each motor for 1.5 seconds
*
*/
void testMotors()
{
	frontRightVal=118;//Set individual motor
	wait1Msec(1500); //Wait 1.5 seconds
	clearMotors(); //clear motor(s)
	backRightVal=118;
	wait1Msec(1500);
	clearMotors();
	frontLeftVal=118;
	wait1Msec(1500);
	clearMotors();
	backLeftVal=118;
	wait1Msec(1500);
	clearMotors();
}
