#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoderr,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderl,       sensorQuadEncoder)
#pragma config(Motor,  port1,           exr,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,           frontr,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backr,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontl,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backl,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           flyr,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           flyl,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armt,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armb,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           exl,          tmotorVex393_MC29, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*THIS IS 241E'S Forked Version*//

/**
 * @file    main.c
 * @brief   This file contains the base for competiton code.
 * @details The three sections include Pre-Auton, Auton, and User
 *          Control.
 *
 * @author
 */


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"




/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Pre-Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period before autonomous when bot cannot move, but minimal code can run
 */
void pre_auton()
{
 bStopTasksBetweenModes = true;
}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when bot is using only code to operate.
 */

task autonomous(){

	startTask(runMotors);


  //u
	auto_spin_flywheel(118,15,true);
	//startTask(auto_flywheel);
	//startTask(auto_drive);
	//startTask(auto_intake);

	/*
	while(true){

		//so this loop doesn't hog the cpu
		wait1Msec(10);
	}
	*/

}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when driver controls the bot
 */
task usercontrol(){

	//startTask(flywheel);
	//startTask(intake);
	//startTask(drive);

	bool initial = true;
	bool unpressed = false;
	bool unpressed2 = false;
	int speed_select = 118;
	bool selpressed = false;

	while (true){
		if(bVEXNETActive){


		  // drivetrain
			if(initial == true){
				//sets drive to a regular state
				motor[backr] = vexRT[Ch2];
				motor[frontr] = vexRT[Ch2];
				motor[backl] = -vexRT[Ch3];
				motor[frontl] = -vexRT[Ch3];
				if (vexRT[Btn5U] == 1){
					initial = false;

				}

			} else if(initial == false){
				//sets the drive to reverse
				motor[backr] = -vexRT[Ch3];
				motor[frontr] = -vexRT[Ch3];
				motor[backl] = vexRT[Ch2];
				motor[frontl] = vexRT[Ch2];
				if(vexRT[Btn6U] == 1){
					initial = true;
				}

			}

			// flywheel
			//defaults: speed_select = 118 && unpressed = false
			//if the button has been unpressed from after turning the motors off
			if(unpressed == false){
				if(vexRT[Btn8D] == 1){
					spin_flywheel(speed_select);
					while(vexRT[Btn8D] == 1){
						wait1Msec(1);
					}
					if(vexRT[Btn8D] == 0){
						unpressed = true;
					}
				}
			}

			//if the button has been unpressed from after turning the motors on
			if(unpressed == true){
				if(vexRT[Btn8D] == 1){
					motor[flyr] = 0;
					motor[flyl] = 0;
					motor[exr] = 0;
					motor[exl] = 0;
					while(vexRT[Btn8D] == 1){
						wait1Msec(1);
					}
					if(vexRT[Btn8D] == 0){
						unpressed = false;
					}
				}
			}

			// intake
			//defaults to this
			//if the button has been unpressed from after turning the motors off
			if(unpressed2 == false){
				if(vexRT[Btn7D] == 1){
					motor[armt] = -75;
					motor[armb] = -75;
					while(vexRT[Btn7D] == 1){
						wait1Msec(1);
					}
					if(vexRT[Btn7D] == 0){
						unpressed2 = true;
					}
				}

			}

			//if the button has been unpressed from after turning the motors on
			if(unpressed2 == true){
				if(vexRT[Btn7D] == 1){
					motor[armt] = 0;
					motor[armb] = 0;
					while(vexRT[Btn7D] == 1){
						wait1Msec(1);
					}
					if(vexRT[Btn7D] == 0){
						unpressed2 = false;

					}
				}

			}


			wait1Msec(10);

		}
	}
}
