#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		motor[leftMotor]  = vexRT[Ch3];   // Left Joystick Y value
    motor[rightMotor] = vexRT[Ch2];   // Right Joystick Y value

		if(vexRT[Btn5U] == 1)
		{
			motor [armMotor] = 60;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor [armMotor] = -60;
		}
		else
		{
			motor [armMotor] = 0;
		}

		if(vexRT[Btn6U] == 1)
		{
			motor [claw] = 50;
		}
		 	else if (vexRT[Btn6D] == 1)
		{
			motor [claw] = -50;
		}
		else
		{
			motor [claw] = 0;
		}



		wait1Msec(5);
}
}
