#pragma config(Motor,  port1,           leftMotor,     tmotorVex269_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           clawMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
		{
		 //Right side of the robot is controlled by the right joystick, Y-axis
		    motor[port2] = vexRT[Ch2];
 	   //Left side of the robot is controlled by the left joystick, Y-axis
 			   motor[port1] = vexRT[Ch3];
		//Claw motor opening
			if(vexRT[Btn8U] == 1)
			{
				motor[clawMotor] = 100;
			}
			else(vexRT[Btn8U] == 0);
			{
				motor[clawMotor] = 0;
			}
//Claw motor closing
	if(vexRT[Btn8D] == 1)
	{
		motor[clawMotor] = -100;
	}
	else(vexRT[Btn8D] == 0);
	{
		motor[clawMotor] = 0;
	}
/////////////////////////
//
//
//Arm motor moving up
	if(vexRT[Btn7U] == 1)
	{
		motor[armMotor] = 100;
	  wait10Msec (0010);
		motor[armMotor] = 0;

	}
/////////////////////////
//
//
//Arm motor moving down
	if(vexRT[Btn7D] == 1)
	{
	motor[armMotor] = -100;
	}
	else(vexRT[Btn7D] == 0);
	{
		motor[armMotor] = 0;
	}
}
}
